services:
  discovery-service:
    image: consul:1.15
    container_name: discovery-service
    ports:
      - '8500:8500'       
      - '8600:8600' 
    expose:
      - '8500'
      - '8600'
    command: "agent -server -bootstrap -ui -bind=0.0.0.0 -client=0.0.0.0"
    volumes:
      - consul-data:/consul/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/v1/status/leader"]
      interval: 10s
      timeout: 5s
      retries: 5

  config-service:
    build: ./config-service
    container_name: config-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    depends_on:
      discovery-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 4
    environment:
      - DISCOVERY_URL=discovery-service
      - DISCOVERY_PORT=8500
      

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - '8081:8081'
    expose:
      - '8081'
    depends_on:
      config-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 4
    environment :
      - DISCOVERY_URL=discovery-service
      - DISCOVERY_PORT=8500
      - CONFIG_URL=http://config-service:9999

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - '8888:8888'
    expose:
      - '8888'
    depends_on:
      config-service:
        condition: service_healthy
    environment : 
      - DISCOVERY_URL=discovery-service
      - DISCOVERY_PORT=8500
      - CONFIG_URL=http://config-service:9999

  task-service:
    build: ./task-service
    container_name: task-service
    ports:
      - '8082:8082'
    expose:
      - '8082'
    depends_on:
      user-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 4
    environment:
      - DISCOVERY_URL=discovery-service
      - DISCOVERY_PORT=8500
      - CONFIG_URL=http://config-service:9999

  project-service:
    build: ./project-service
    container_name: project-service
    ports:
      - '8083:8083'
    expose:
      - '8083'
    depends_on:
      task-service:
        condition: service_healthy
    environment:
      - DISCOVERY_URL=discovery-service
      - DISCOVERY_PORT=8500
      - CONFIG_URL=http://config-service:9999

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - '8084:8084'
    expose:
      - '8084'
    depends_on:
      user-service:
        condition: service_healthy
    environment:
      - DISCOVERY_URL=discovery-service
      - DISCOVERY_PORT=8500
      - CONFIG_URL=http://config-service:9999

volumes:
  consul-data: